Filesystem Library & setclipboard fix
SecondNewtonLaw/RbxStu pull request #3
Opened 2024-05-05 20:08 UTC by nhisoka

**Added Filesystem library**
`readfile`, `writefile`, `listfiles`, `makefolder`, `appendfile`,  `delfile`, `delfolder`, `isfile` , `isfolder`, `dofile`, `loadfile`

**Also fixed setclipboard**

2024-05-05 21:35 UTC, SecondNewtonLaw requested changes

2024-05-05 21:35 UTC, SecondNewtonLaw commented on Environment/Environment.cpp
> +    lua_pop(L, 1);
Unnecessary pop. Remove.

2024-05-05 21:35 UTC, SecondNewtonLaw commented on Environment/Environment.cpp
> +    HWND hwnd = GetDesktopWindow();
You don't need this.

2024-05-05 21:35 UTC, SecondNewtonLaw commented on Environment/Environment.cpp
> +    memcpy(GlobalLock(hg), data, strlen(data) + 1);
https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globallock

Global lock may return a nullptr, this will cause UB, fix.

2024-05-05 21:38 UTC, SecondNewtonLaw requested changes

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +        return 0;
Unnecessary return.

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +std::vector<std::string> disallowed_extensions = {
Mark as const if not modified.

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +const auto pUtilities{Module::Utilities::get_singleton()};
Avoid doing this.

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +        path += ".txt";
Not standard behaviour, remove.

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +                luaG_runerrorL(L, "attempt to escape directory");
Change error to "Illegal extension" or a variation. This is not a directory escape.

2024-05-05 21:38 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +// Created by nhisoka on 5/5/2024.
Don't change Created header.

2024-05-05 21:39 UTC, SecondNewtonLaw requested changes

2024-05-05 21:39 UTC, SecondNewtonLaw commented on Scanner.cpp
> +// Created by nhisoka on 3/5/2024.
Don't change created header.

2024-05-05 21:41 UTC, SecondNewtonLaw requested changes

2024-05-05 21:41 UTC, SecondNewtonLaw commented on Utilities.cpp
> +#define _CRT_SECURE_NO_WARNINGS
Don't disable the safety of MSVCs' CRT.

2024-05-05 21:41 UTC, SecondNewtonLaw commented on Utilities.cpp
> +    if (!std::filesystem::exists(this->location + ("\\workspace")))
This is part of the FileSystem Library, this code should not concern the Utilities class.

2024-05-05 21:41 UTC, SecondNewtonLaw commented on Utilities.hpp
> +        std::string location;
Does not concern the Utilities class.

2024-05-05 21:42 UTC, SecondNewtonLaw commented on Environment/Environment.cpp
> +    lua_pop(L, 1);
Besides that, Unnecessary luaL_tolstring, use lua_tostring()

2024-05-06 11:20 UTC, SecondNewtonLaw requested changes
I will check up a bit more when I get to my desktop later, for now, cheers

2024-05-06 11:20 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.cpp
> +// Created by Dottik on 5/5/2024.
Fix creation date

2024-05-06 11:20 UTC, SecondNewtonLaw commented on Environment/FilesystemLibrary.hpp
> +   static std::string location;
Static variables should be only accessible through getters and setters for consistency.

2024-05-06 11:20 UTC, SecondNewtonLaw commented on Scanner.cpp
> +// Created by Dottik on 3/5/2024.
Fix creation date.

2024-05-06 11:59 UTC, nhisoka commented on Scanner.cpp
> +// Created by Dottik on 3/5/2024.
to what creation date should i set it?

2024-05-06 12:19 UTC, SecondNewtonLaw commented on Scanner.cpp
> +// Created by Dottik on 3/5/2024.
original one @nhisoka

2024-05-06 12:28 UTC, nhisoka commented on Scanner.cpp
> +// Created by Dottik on 3/5/2024.
> original one @nhisoka

i did

2024-05-08 01:32 UTC, merged